### ISSUE TITLE
Problems with cuda_fp16 and Eigen Library

### ISSUE THREAD

**Issue by waredjeb** [ComputationalRadiationPhysics/cupla#131] opened 2019-10-23 17:10 UTC
Hello,
I was porting a code from cuda using cupla,  and I noticed that some errors are generated when  ```<cupla/config/GpuCudaRt.hpp> ``` is included before the ```#include```s of the ```Eigen``` library. In the detail:
Errors are generated when I have a structure like this:
```
#include <cuda/config/GpuCudaRt.hpp>
#include <Eigen/Core>
#include <Eigen/Eigenvalues>
```
While in the following way, I get no errors:
```
#include <Eigen/Core>
#include <Eigen/Eigenvalues>
#include <cuda/config/GpuCudaRt.hpp>
```
In particular the errors are the following:
```
/usr/local/cuda/include/cuda_fp16.h(3002): error: incomplete type is not allowed
/usr/local/cuda/include/cuda_fp16.h(3002): error: expected an identifier
/usr/local/cuda/include/cuda_fp16.h(3002): error: inline specifier allowed on function declarations only
/usr/local/cuda/include/cuda_fp16.h(3002): error: expected a ";"
/usr/local/cuda/include/cuda_fp16.h(3008): error: incomplete type is not allowed
/usr/local/cuda/include/cuda_fp16.h(3008): error: expected an identifier
/usr/local/cuda/include/cuda_fp16.h(3008): error: inline specifier allowed on function declarations only
/usr/local/cuda/include/cuda_fp16.h(3008): error: expected a ";"
/usr/local/cuda/include/cuda_fp16.hpp(2018): error: name followed by "::" must be a class or namespace name
/usr/local/cuda/include/cuda_fp16.hpp(2018): error: expected an identifier
/usr/local/cuda/include/cuda_fp16.hpp(2018): error: inline specifier allowed on function declarations only
/usr/local/cuda/include/cuda_fp16.hpp(2018): error: expected a ";"
```
Is there a way to solve this problem, where for some reasons I would need to include the GpuCudaRt.hpp before the Eigen library?

I'm on CentOS7 with cuda-10.1 and gcc 8.3.1
In the following the flags for the compilation:
```
export CXXFLAGS="-m64 -std=c++14 -g -O2 -DALPAKA_DEBUG=0 -DALPAKA_CUDA_ARCH=60:70:75 -I$CUDA_ROOT/include -L$CUDA_ROOT/lib64 -lcudart -lcuda -I$ALPAKA_ROOT/include -I$CUPLA_ROOT/include -I$SLC7_BASE/include -I$EIGEN_BASE -I$TBB_BASE/include -L$TBB_BASE/lib -ltbb" 
HOST_FLAGS="-fopenmp -pthread -fPIC -ftemplate-depth-512 -Wall -Wextra -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-attributes -Wno-reorder -Wno-sign-compare"

NVCC="$CUDA_ROOT/bin/nvcc"
NVCC_FLAGS="-ccbin $CXX -w -lineinfo --expt-extended-lambda --expt-relaxed-constexpr --use_fast_math --ftz=false --cudart shared"```

**Comment by sbastrakov** [comment] 2019-10-23 20:48
Thanks for a detailed description. I will try to reproduce tomorrow. Our general idea is to include cupla before the CUDA stuff, which is however the way that does not work for you. The issues are probably caused by Eigen including CUDA headers as well. But it is unclear why the other order works then.

**Comment by sbastrakov** [comment] 2019-10-23 21:08
Needs to be checked, but we probably need to add defines for [CUDA `__half` and `__half2` types](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH____HALF__MISC.html). Kinda like what #118 did for `int3` and `float3`.

**Comment by psychocoderHPC** [comment] 2019-10-23 21:22
@waredjeb  Is the Eigen lib also using cuda internally?
Cupla ships internally a few defines to rename functions `cuda*` into `cupla*`. This has the side effect that you must include cupla always after all external libs which need direct access to cuda. @sbastrakov thats the reason why include cupla late is working.
I like to remove this and allow the user to chose if this renamings are required.

**Comment by sbastrakov** [comment] 2019-10-23 21:33
Yes, Eigen includes CUDA stuff. Then we need to update our readme, that explicitly tells to include cupla before CUDA headers.

**Comment by waredjeb** [comment] 2019-10-24 08:56
@sbastrakov @psychocoderHPC  thanks for the quick replies!

**Comment by waredjeb** [comment] 2019-10-24 10:43
@sbastrakov Sorry I forgot to reply to the question, I will try your suggestion!

**Comment by sbastrakov** [comment] 2019-11-07 11:01
@waredjeb should I close this issue? Not sure if you found time to try my later suggestion.

**Comment by waredjeb** [comment] 2019-11-07 11:18
@sbastrakov sorry for the late answer, I tried your suggestion. But in this way I got some errors: 
```.../Eigen/src/Core/arch/GPU/Half.h(583): error: identifier "hceil" is undefined```
```.../Eigen/src/Core/arch/GPU/Half.h(575): error: identifier "hfloor" is undefined```

**Comment by sbastrakov** [comment] 2019-11-07 12:24
Thanks for trying, sorry it did not work out. Closing the issue.

**Closed by sbastrakov** 2019-11-07 12:24 UTC
Labels: bug
